services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "mydatabase" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '15432:5432'
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/mydatabase -user=myuser -password=secret -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/migrations:/flyway/sql
    depends_on:
      - postgres
  storage:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: test-user
      MINIO_ROOT_PASSWORD: secret-secret
    command: "server /data"
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
    ports:
      - '9001:9000'
volumes:
  db_data:
    driver: local
  minio_data:
    driver: local