spring:
  application:
    name: tink-ab
  datasource:
    url: jdbc:postgresql://localhost:15432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      path: /api/v1
  kafka:
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USER:admin}" password="${KAFKA_PASSWORD:admin-secret}";
  docker:
    compose:
      enabled: false

storage:
  access-key: test-user
  secret-key: secret-secret
  endpoint: http://localhost:9001
  bucket-name: test-bucket
  region: us-east-1

jwt:
  secret: 47397FFF432646294A404E635266556A586E3272357538782F4125442A472D4B
  issuer: sejapoe

  #management:
  ##  server:
  ##    port: 8091
  #  endpoints:
  #    web:
  #      exposure:
  #        include: info,health,prometheus
  ## info,health,prometheus
  ##      base-path:  /
  ##      path-mapping:
  ##        prometheus: metrics
  metrics:
    #    tags:
    #      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
##    export:
##      prometheus:
##        enabled: true
##  prometheus:
##    metrics:
##      export:
##        enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    shutdown:
      enabled: true
    info:
      env:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, shutdown, beans
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
