name: module-api
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Execute Gradle Assemble
        run: ./gradlew :api:clean :api:assemble
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/api/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          update-comment: true
          title: "Jacoco Report"
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Execute Gradle Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
  openapi-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Generate OpenAPI specs
        env:
          SPRING_DOCKER_COMPOSE_ENABLED: true
        run: ./gradlew :api:generateOpenApiDocs -x :api:test
      - name: Run OpenAPI Diff
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: --fail-on-incompatible api/openapi.yaml api/build/openapi.json --markdown ./api/openapi-diff-report.md
      - name: Create OpenAPI DIff Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const prefix = "## OpenAPI difference report";

            let content = fs.readFileSync('api/openapi-diff-report.md', 'utf8');
            content = prefix + "\n" + content;

            const comments = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const existingComment = comments.data.find(comment => comment.body.startsWith(prefix));

            if (!!existingComment) {
              await github.rest.issues.updateComment({
                comment_id: existingComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: content
              });
            } else {
              core.info('No existing comment found. Creating a new one.');
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: content
              });
            }
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Execute Gradle Test
        run: ./gradlew :api:clean :api:test
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/api/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75
          update-comment: true
          title: "Jacoco Report"
  deploy:
    runs-on: ubuntu-latest
    needs: [ build, checkstyle, openapi-diff, unit-tests ]
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
      - name: Docker login
        working-directory: ./api
        env:
          DOCKER_USERNAME: ${{ secrets.dockerhub_username }}
          DOCKER_PASSWORD: ${{ secrets.dockerhub_password }}
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" docker.io
      - name: Build the Docker image
        working-directory: ./api
        run: docker build . --file Dockerfile --tag ${{secrets.dockerhub_username}}/${{secrets.dockerhub_repo_name}}:${{steps.vars.outputs.tag}}
      - name: Publish dockerimage to docker hub
        working-directory: ./api
        run: docker push ${{secrets.dockerhub_username}}/${{secrets.dockerhub_repo_name}}:${{steps.vars.outputs.tag}}
      - name: Build Docker image with latest tag
        working-directory: ./api
        run: docker build . --file Dockerfile --tag ${{secrets.dockerhub_username}}/${{secrets.dockerhub_repo_name}}:latest
      - name: Publish dockerimage to docker hub
        working-directory: ./api
        run: docker push ${{secrets.dockerhub_username}}/${{secrets.dockerhub_repo_name}}:latest