name: tests
on: [ pull_request ]
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup gradle
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
      - name: Execute Gradle Build
        run: ./gradlew build
      - name: Generate OpenAPI specs
        run: ./gradlew generateOpenApiDocs
      - name: Run OpenAPI Diff
        uses: docker://openapitools/openapi-diff:latest
        with:
          args: --fail-on-incompatible openapi.yaml build/openapi.json --markdown ./openapi-diff-report.md
      - name: Read file content
        id: read-file
        run: |
          echo "::set-output name=content::$(cat openapi-diff-report.md)"
      - name: Create Comment
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const content = process.env.content;
            
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: content
            });
            
            core.info(content); // Output content to logs